version: "build-{build}"

image: Visual Studio 2022

environment:
  EMAIL:
    secure: no0uCdrnaWY/44Nfx6Tg+zE71d59XA/0nnJT9LznqtQ=
  ACCESS_TOKEN:
    secure: JIG9V7Fvjdpl1FvBGSTbv5s29nbAL3RcHiHgSaNC7WwoO2jUOBviIPHvQz2TcI/v

# install:
#   - pwsh: choco install docfx -y | Out-Null

build_script:
  - pwsh: |
      dotnet restore .\src\Disqord.sln 
      dotnet build .\src\Disqord.sln -c "Release" --no-restore -p:NoWarn=1591

after_build:
  - pwsh: |
      $HasRepoTag = $Env:APPVEYOR_REPO_TAG -eq "true" 
      $VersionSuffix = "$Env:APPVEYOR_BUILD_NUMBER" 
      Invoke-Expression "dotnet pack .\src\Disqord.sln -c Release -o .\artifacts --no-restore --no-build $(!$HasRepoTag ? "--version-suffix=$VersionSuffix" : $null)"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
# docfx docs/docfx.json

# after_deploy: # docfx
#   - pwsh: |
#       $Directory = "gh-pages\\$($HasRepoTag ? 'stable' : 'nightly')\\"
#       git config --global credential.helper store
#       Add-Content "$HOME\.git-credentials" "https://$($Env:ACCESS_TOKEN):x-oauth-basic@github.com`n"
#       git config --global user.email $Env:EMAIL
#       config --global user.name "Quahu"
#       clone -q --branch=gh-pages https://github.com/Quahu/Disqord.git gh-pages
#       if (!(Test-Path $Directory))
#       {
#           mkdir $Directory
#       }
#       else
#       {
#           Remove-Item "$Directory*" -Recurse
#       }
#       Copy-Item ".\docs\_site\*" -Destination $Directory -Force -Recurse
#       cd $Directory
#       add .
#       git commit --allow-empty -m "Updated $Directory to $VersionSuffix."
#       push origin gh-pages

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

test: off

artifacts:
  - path: .\artifacts\*

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/disqord/api/v2/package/
    symbol_server: https://www.myget.org/F/disqord/api/v2/symbolpackage/
    api_key:
      secure: XW7HgRlmPz8/YHNSCAjAzBbYvgTx1dVSA+OU8AmuU6OamtFJnUr2CCAbHukPg0r7
    on:
      branch: master
      appveyor_repo_tag: false
  - provider: NuGet
    symbol_server: https://www.nuget.org/api/v2/symbolpackage
    api_key:
      secure: Q3cqDs8CwgBcw4zMx1xTUpq/vuPKAHQ+qtRsoK059qxnmugRUsNzWmN3ZTXmycbm
    on:
      appveyor_repo_tag: true
